[package]
name = "lorevault"
version = "0.2.0"
edition = "2021"


[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
git2 = "0.18.3"
regex = "1.10.4"
reqwest = { version = "0.12.2", features = ["blocking", "json"] }
serde = { version = "1.0.197", features = ["derive"] }
sha3 = "0.10.8"
tar = "0.4.40"
tempfile = "3.10.1"
toml = "0.8.12"
xz2 = "0.1.7"
zip = "0.6.6"
