var.rust_git_commit="ea504e6bf11a23bb010b7b98a58a97ec2dcd0489"
var.rust_git_repo="https://github.com/rust-lang/rustlings.git"
var.favorite_black_cat="Freddy"

[[directory]]
path="program_src"
sources=["https://invalid.domaindoesnotexist#{{rust_git_commit}}:src","{{rust_git_repo}}#{{rust_git_commit}}:src"]

[[directory]]
path="/"
sources=["{{SELF_PARENT}}/testfolder/subfolder"]

[[file]]
path="program_src/main.rs"
tags=["replace_main"]
sources=["{{SELF_PARENT}}/../src/main.rs"]

[[file]]
path="Dracula.txt"
sources=["https://www.gtenberg.org/cache/epub/345/pg345.txt",
"https://www.gutenberg.org/cache/epub/345/pg345.txt"]#To ensure linebreaks are allowed
[[file.edit]]
type="replace"
from="Dracula"
to="{{favorite_black_cat}}"
[[file.edit]]
type="replace"
from="DRACULA"
to="{{favorite_black_cat}}"

[[include]]
path="/included/"
with_tags=["testfolder"]
tags=["inc"]
config="{{SELF_ROOT}}/included2.toml"
