# If the tag is given, the two files clash
[[include]]
config="{{SELF_ROOT}}/included1.toml"
with_tags=["main"]
tags=["inc"]

[[include]]
config="{{SELF_ROOT}}/included1.toml"
with_tags=["main"]
tags=["inc"]
