# Even though the included file has a tag and the local one does not, it should not be allowed.
[[include]]
config="{{SELF_ROOT}}/included1.toml"
with_tags=["main"]
tags=["inc"]

[[file]]
path="included/main.rs"
sources=["{{SELF_ROOT}}/../src/main.rs"]