var.local_var="local"
[[include]]
config="{{SELF_ROOT}}/included1.toml"
with_tags=[] #Should load no files
subdir="shouldnotexist"

[[include]]
config="{{SELF_ROOT}}/included1.toml"
with_tags=["main"]
hash = "69C2DA8874560C982F896938B744752F304E35EEEC63E7F5967E4E68FAD03070"

[[include]]
tags=["subfolder"]
config="{{SELF_ROOT}}/included1.toml"
subdir="subfolder"
with_tags=["main"]

[[file]]
path="{{local_var}}/other/main.rs"
sources=["{{SELF_ROOT}}/../src/main.rs"]

[[file]]
tags=["conflict"] # this can not be active together with subfolder
path="subfolder/included/main.rs"
sources=["{{SELF_ROOT}}/../src/main.rs"]

