var.rust_git_commit="ea504e6bf11a23bb010b7b98a58a97ec2dcd0489"
var.rust_git_repo="https://github.com/rust-lang/rustlings.git"

[[file]]
path="rustlings_readme.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="/description.txt" # check if / is removed
[[file.source]]
type="text"
content="This is a test file. \nI hope you like it."

[[file]]
path="/subfolder/main.rs"
sources=["{{SELF_ROOT}}/../src/main.rs"]

[[file]]
path="/subfolder/fromarchive1.txt"
[[file.source]]
type="archive"
archive="{{SELF_ROOT}}/testarchive.zip"
path="/file1.txt"

[[file]]
tags=["file2"]
hash = "7C4D8154285FA166277835810027AE5970AE388CF7A78209DDAC184880B46C8C"
path="/subfolder/fromarchive2.txt"
sources=["{{SELF_ROOT}}/testarchive.zip:subfolder/file2.txt","{{SELF_ROOT}}/testarchive.tar.xz:/subfolder/file2.txt"]

