#This can be used to check if remote rpos are cached correctly.
var.rust_git_commit="ea504e6bf11a23bb010b7b98a58a97ec2dcd0489"
var.rust_git_repo="https://github.com/rust-lang/rustlings.git"

var.lv_repo="https://github.com/JanNeuendorf/lorevault.git"
var.lv_commit="3132eec850323fd2f845249e71dbb5ffdd405f5c"

[[file]]
path="alias1.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:README.md"] # "/" should not matter

[[file]]
path="alias2.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="alias3.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="alias4.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="alias5.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="alias6.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="alias7.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="alias8.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="alias9.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="alias10.md"
sources=["{{rust_git_repo}}#{{rust_git_commit}}:/README.md"]

[[file]]
path="second_alias1.md"
sources=["{{lv_repo}}#{{lv_commit}}:/README.md"]