
# ██       ██████  ██████  ███████ ██    ██  █████  ██    ██ ██   ████████ 
# ██      ██    ██ ██   ██ ██      ██    ██ ██   ██ ██    ██ ██      ██    
# ██      ██    ██ ██████  █████   ██    ██ ███████ ██    ██ ██      ██    
# ██      ██    ██ ██   ██ ██       ██  ██  ██   ██ ██    ██ ██      ██    
# ███████  ██████  ██   ██ ███████   ████   ██   ██  ██████  ███████ ██    
#                                                                          

var.lorevault_github="https://github.com/JanNeuendorf/lorevault.git"

[[file]]
path="readme.md"
sources=["{{lorevault_github}}#main:README.md"]
[[file.edit]]
type="insert"
position="start"
content="""

**This README is for the latest version of Lorevault!**

"""

